### ISSUE TITLE
problem with yq installer

### ISSUE THREAD

**Issue by yogit2020** [webinstall/webi-installers#438]
when there is if condition present in yaml. yq can not parse it. Example in below yaml i want to update value for storage from 100M to 1G

yq -i eval '.spec.resources.requests.storage = "1G" ' <file name> Fails .
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-db-vol-claim-local
spec:
  {{- if eq (.Values.storage.class | toString) "abc" }}
  storageClassName: abc
  {{- else if eq (.Values.storage.class | toString) "manual" }}
  storageClassName: manual
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
```
